apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Elmer-EKS-cluster-A
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    minSize: 2
    desiredCapacity: 2
    maxSize: 2